/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ENABLE_NLS 1

#define GETTEXT_PACKAGE PACKAGE_NAME

#ifndef HAVE_STDBOOL_H
//#define HAVE_STDBOOL_H
#endif

#ifndef HAVE_STDINT_H
//#define HAVE_STDINT_H
#endif

#ifndef HAVE_STDLIB_H
//#define HAVE_STDLIB_H
#endif
#define LOCALEDIR PACKAGE_LOCALE_DIR

#define PACKAGE_DATADIR "/usr/local/share"

#define PACKAGE_LIBDIR "/usr/local/lib/x86_64-linux-gnu"

#define PACKAGE_LIBEXECDIR "/usr/local/libexec"

#define PACKAGE_LOCALE_DIR "/usr/local/share/locale"

#define PACKAGE_NAME "emeus"

#define PACKAGE_STRING "emeus-0.99.1"

#define PACKAGE_VERSION "0.99.1"

#define _EMEUS_PUBLIC __attribute__((visibility("default")))

