#!/bin/bash
# Build all binary variations of shoes. This runs under
# my crontab so user name may not be set up for chroot
#schroot -c debx86 -u ccoupe -- ~/Projects/shoes3/crontasks/nbuild-shoes-lin64
~/Projects/shoes3/crontasks/nbuild-shoes-xlin64
~/Projects/shoes3/crontasks/nbuild-shoes-xwin7
# ssh to Mac mini and build.
#~/Projects/shoes3/crontasks/nbuild-shoes-mavericks
~/Projects/shoes3/crontasks/nbuild-shoes-yosemite
# ssh to pi3 and build
#~/Projects/shoes3/crontasks/nbuild-shoes-rpi
~/Projects/shoes3/crontasks/nbuild-shoes-xrpi
# start freebsd11 VM, if needed,  ssh in and build
~/Projects/shoes3/crontasks/nbuild-shoes-bsd
