#!/bin/bash
ssh ccoupe@192.168.1.3 <<'ENDSSH'
echo "Build Shoes OSX 10.9 Mavericks"
source .bashrc
export PATH=$PATH:/usr/local/bin
echo $PATH
rvm use 2.3.4
cd /Users/ccoupe/Projects/shoes3
rm -f build_target
rake osx:setup:xmavericks
rake
rake package
rake clobber
ENDSSH
ls -ld /home/ccoupe/Projects/shoes3/pkg/*osx-10.9.tgz
