#!/bin/bash
ssh ccoupe@mini <<'ENDSSH'
echo "Build Shoes OSX 10.10 Yosemite"
PATH=/usr/local/bin:$PATH
source ~/.bashrc
#rvm use 2.3.6
cd /Users/ccoupe/Projects/shoes3
rm -f build_target
rake setup:osx
rake
rake package
rake clobber
ENDSSH
ls -ld /home/ccoupe/Projects/shoes3/pkg/*osx-10.10.tgz
