#!/bin/sh
echo "Build Shoes X86_64 for Linux"
cd /home/ccoupe/Projects/shoes3
rm -rf build_target
rake setup:xlin64
rake
rake package
#rake clobber # we want the files
rm build_target
ls -ld pkg/*-x86_64.install

