#!/bin/bash
echo "Build Shoes GTK Widgets for MinGW32 Windows"
source ~/bin/bash-chroot
source ~/.rvm/scripts/rvm
cd /home/ccoupe/Projects/shoes3
rm -f build_target
rvm use 2.3.6
rake linux:setup:xwin7
rake
rake package
rake clobber
ls -ld pkg/*.exe
